"""普通运行配置。

这里放不属于密钥的配置项；API Key、base_url 等敏感信息继续放在 .env。
"""

DEBUG_AGENT = True
MAX_GRAPH_STEPS = 8
BASH_PATH = "bash"
MODEL = "deepseek-v4-flash"

# Docker sandbox settings. The project is copied to a temporary sanitized
# directory before mounting, so secrets such as .env are not exposed.
DOCKER_IMAGE = "python:3.12-slim"
DOCKER_TIMEOUT_SECONDS = 10
DOCKER_MEMORY = "256m"
DOCKER_CPUS = "0.5"
DOCKER_OUTPUT_LIMIT = 4000
FILE_READ_CHUNK_LINES = 120
FILE_READ_OUTPUT_LIMIT = 4000

PARENT_FILE_READ_LINES = 30
PARENT_FILE_READ_OUTPUT_LIMIT = 2000

FILE_AGENT_CHUNK_LINES = 160
FILE_AGENT_MAX_CHUNKS = 30
FILE_AGENT_NOTES_LIMIT = 12000
LARGE_FILE_CHUNK_LINES = 220
LARGE_FILE_MAX_CHUNKS = 80
LARGE_FILE_MAP_WORKERS = 4
LARGE_FILE_SUMMARY_LIMIT = 16000

SUBAGENT_MAX_STEPS = 12
SUBAGENT_CONTEXT_MESSAGE_LIMIT = 8
SUBAGENT_RESULT_LIMIT = 6000
