"""Non-secret runtime configuration.

API keys and provider endpoints stay in .env. This file keeps ordinary
development settings that are safe to commit.
"""

DEBUG_AGENT = True
MAX_GRAPH_STEPS = 16
BASH_PATH = "bash"
MODEL = "deepseek-v4-flash"

# Docker sandbox settings. The project is copied to a temporary sanitized
# directory before mounting, so secrets such as .env are not exposed.
DOCKER_IMAGE = "python:3.12-slim"
DOCKER_TIMEOUT_SECONDS = 10
DOCKER_MEMORY = "256m"
DOCKER_CPUS = "0.5"
DOCKER_OUTPUT_LIMIT = 4000
FILE_READ_CHUNK_LINES = 120
FILE_READ_OUTPUT_LIMIT = 4000

PARENT_FILE_READ_LINES = 30
PARENT_FILE_READ_OUTPUT_LIMIT = 2000

FILE_AGENT_CHUNK_LINES = 160
FILE_AGENT_MAX_CHUNKS = 30
FILE_AGENT_NOTES_LIMIT = 12000
LARGE_FILE_CHUNK_LINES = 220
LARGE_FILE_MAX_CHUNKS = 80
LARGE_FILE_MAP_WORKERS = 4
LARGE_FILE_SUMMARY_LIMIT = 16000

SUBAGENT_MAX_STEPS = 16
SUBAGENT_CONTEXT_MESSAGE_LIMIT = 8
SUBAGENT_RESULT_LIMIT = 6000

SKILLS_DIR = "skills"
SKILL_FILE_NAME = "SKILL.md"
SKILL_READ_OUTPUT_LIMIT = 8000

RECENT_MESSAGE_LIMIT = 12
SUMMARY_TRIGGER_MESSAGE_LIMIT = 40
SUMMARY_TRIGGER_CHAR_LIMIT = 24000
SESSION_SUMMARY_MAX_CHARS = 4000
SUMMARY_SOURCE_CHAR_LIMIT = 12000

MEMORY_ENABLED = True
MEMORY_DB_HOST = "localhost"
MEMORY_DB_PORT = 5432
MEMORY_DB_NAME = "learn_agent"
MEMORY_DB_USER = "postgres"
MEMORY_DB_PASSWORD = "postgres"
DEFAULT_SESSION_ID = "default"
MEMORY_RETRIEVAL_LIMIT = 6
MEMORY_EXTRACTION_ENABLED = True
MEMORY_EXTRACTION_ASYNC = True
MEMORY_EXTRACTION_INTERVAL_TURNS = 5
MEMORY_EXTRACTION_MIN_CHARS = 1200
MEMORY_EXTRACTION_HINT_KEYWORDS = [
    "记住",
    "保存",
    "偏好",
    "约定",
    "规则",
    "以后",
    "长期",
    "remember",
    "preference",
    "always",
]
MEMORY_MIN_IMPORTANCE = 3
MEMORY_EXTRACT_SOURCE_CHAR_LIMIT = 12000

AGENT_EVENTS_ENABLED = True
AGENT_EVENTS_POSTGRES_ENABLED = True
AGENT_EVENTS_CONSOLE_ENABLED = False
AGENT_EVENTS_FILE_ENABLED = False
AGENT_EVENTS_FILE_PATH = "logs/agent_events.jsonl"
AGENT_EVENTS_PAYLOAD_PREVIEW_LIMIT = 1000
AGENT_EVENTS_ASYNC_WRITE = True
AGENT_EVENTS_BATCH_SIZE = 50
AGENT_EVENTS_FLUSH_INTERVAL_SECONDS = 1.0
AGENT_EVENTS_QUEUE_MAX_SIZE = 1000

START_DB = (
    r"docker run -d -p 5432:5432 "
    r"-e POSTGRES_USER=postgres "
    r"-e POSTGRES_PASSWORD=postgres "
    r"-e POSTGRES_DB=learn_agent "
    r"-v E:\docker\pgvector2\data:/var/lib/postgresql/data "
    r"--name pgvector2 pgvector/pgvector:pg17"
)
