"""Non-secret runtime configuration.

Committed defaults live here. Deployment-specific values and secrets can be
overridden with environment variables or the Core user-level .env file.
"""

from src.config.env import env_bool, env_float, env_int, env_str


DEBUG_AGENT = env_bool("LEARN_AGENT_DEBUG", False)
MAX_GRAPH_STEPS = 20
MAX_TOOL_CALLS_PER_TURN = 12
BASH_PATH = "bash"
MODEL = env_str("LEARN_AGENT_MODEL", "deepseek-v4-flash")

DOCKER_IMAGE = "python:3.12-slim"
DOCKER_TIMEOUT_SECONDS = 10
DOCKER_MEMORY = "256m"
DOCKER_CPUS = "0.5"
DOCKER_OUTPUT_LIMIT = 4000
FILE_READ_CHUNK_LINES = 200
FILE_READ_OUTPUT_LIMIT = 8000
ENTIRE_FILE_MAX_LINES = 300

PARENT_FILE_READ_LINES = 80
PARENT_FILE_READ_OUTPUT_LIMIT = 5000

FILE_AGENT_CHUNK_LINES = 160
FILE_AGENT_MAX_CHUNKS = 30
FILE_AGENT_NOTES_LIMIT = 12000
LARGE_FILE_CHUNK_LINES = 220
LARGE_FILE_MAX_CHUNKS = 80
LARGE_FILE_MAP_WORKERS = 4
LARGE_FILE_SUMMARY_LIMIT = 16000

SUBAGENT_MAX_STEPS = 32
SUBAGENT_CONTEXT_MESSAGE_LIMIT = 8
SUBAGENT_RESULT_LIMIT = 6000

SKILLS_DIR = "skills"
SKILL_FILE_NAME = "SKILL.md"
SKILL_READ_OUTPUT_LIMIT = 8000

RECENT_MESSAGE_LIMIT = 12
SUMMARY_TRIGGER_MESSAGE_LIMIT = 40
SUMMARY_TRIGGER_CHAR_LIMIT = 24000
SESSION_SUMMARY_MAX_CHARS = 4000
SUMMARY_SOURCE_CHAR_LIMIT = 12000

MEMORY_ENABLED = True
MEMORY_DB_URL = env_str("LEARN_AGENT_DATABASE_URL", "")
MEMORY_DB_HOST = env_str("LEARN_AGENT_DB_HOST", "127.0.0.1")
MEMORY_DB_PORT = env_int("LEARN_AGENT_DB_PORT", 5432)
MEMORY_DB_NAME = env_str("LEARN_AGENT_DB_NAME", "learn_agent")
MEMORY_DB_USER = env_str("LEARN_AGENT_DB_USER", "postgres")
MEMORY_DB_PASSWORD = env_str("LEARN_AGENT_DB_PASSWORD", "postgres")
DEFAULT_SESSION_ID = "default"
MEMORY_RETRIEVAL_LIMIT = 6
MEMORY_BOOTSTRAP_LIMIT = 4
MEMORY_CONTEXT_CHAR_LIMIT = 6000
MEMORY_EXTRACTION_ENABLED = True
MEMORY_EXTRACTION_ASYNC = True
MEMORY_EXTRACTION_INTERVAL_TURNS = 5
MEMORY_EXTRACTION_MIN_CHARS = 1200
MEMORY_EXTRACTION_HINT_KEYWORDS = [
    "记住",
    "保存",
    "偏好",
    "约定",
    "规则",
    "以后",
    "长期",
    "remember",
    "preference",
    "always",
]
MEMORY_MIN_IMPORTANCE = 3
MEMORY_EXTRACT_SOURCE_CHAR_LIMIT = 12000

AGENT_EVENTS_ENABLED = True
AGENT_EVENTS_POSTGRES_ENABLED = True
AGENT_EVENTS_CONSOLE_ENABLED = False
AGENT_EVENTS_FILE_ENABLED = False
AGENT_EVENTS_FILE_PATH = "logs/agent_events.jsonl"
AGENT_EVENTS_PAYLOAD_PREVIEW_LIMIT = 1000
AGENT_EVENTS_ASYNC_WRITE = True
AGENT_EVENTS_BATCH_SIZE = 50
AGENT_EVENTS_FLUSH_INTERVAL_SECONDS = 1.0
AGENT_EVENTS_QUEUE_MAX_SIZE = 1000

CORE_HOST = env_str("LEARN_AGENT_CORE_HOST", "127.0.0.1")
CORE_PORT = env_int("LEARN_AGENT_CORE_PORT", 18765)
CORE_MAX_MESSAGE_BYTES = 1_048_576
CORE_SHUTDOWN_TIMEOUT_SECONDS = env_float("LEARN_AGENT_CORE_SHUTDOWN_TIMEOUT_SECONDS", 10)
CORE_CONNECT_TIMEOUT_SECONDS = env_float("LEARN_AGENT_CORE_CONNECT_TIMEOUT_SECONDS", 3)
CORE_DAEMON_STARTUP_TIMEOUT_SECONDS = env_float("LEARN_AGENT_DAEMON_STARTUP_TIMEOUT_SECONDS", 15)
CORE_DAEMON_STOP_TIMEOUT_SECONDS = env_float("LEARN_AGENT_DAEMON_STOP_TIMEOUT_SECONDS", 15)
CORE_AGENT_WORKERS = env_int("LEARN_AGENT_CORE_AGENT_WORKERS", 4)
CORE_RUNTIME_DIR = ""
PG_DUMP_PATH = env_str("LEARN_AGENT_PG_DUMP_PATH", "")
POSTGRES_DOCKER_CONTAINER = env_str("LEARN_AGENT_DB_CONTAINER", "learn-agent-postgres")
